### ISSUE TITLE
errors compiling DemoFailure (and DemoSuccess)

### ISSUE THREAD

**Issue by jgravois** [snodnipper/vector-tile-esri-issues#1]
please forgive the bumbling questions of a lowly web developer :innocent:, but i'd really like to learn how to run this demo myself.

these are the steps i took:
1. installed the project dependencies (protoc, wget, gradle)
2. executed `./run.sh`. this created a `temp` directory w/ demo code
3. based on info in [StackOverflow](http://stackoverflow.com/questions/16137713/how-to-run-a-java-program-from-the-command-line/33149828#33149828), i was able to compile and execute the generic stubbed app successfully.

```
$ cd temp/src/main/java
$ javac App.java
$ java App
Hello world.
```
4. tried calling `javac DemoFailure.java` to compile similarly and encountered an error indicating that `com.google.protobuf` could not be found.
5. downloaded [`v3.0.0`](https://github.com/google/protobuf/releases/tag/v3.0.0) java binaries and placed them manually in the folder below
```
temp/src/main/java/com/google/protobuf
```
this got me down from 100 errors to 69 errors.  a few of the remaining complaints can be found below.

```
./uk/os/util/CompressUtil.java:20: error: package org.slf4j does not exist
import org.slf4j.LoggerFactory;

./com/google/protobuf/Descriptors.java:33: error: package com.google.protobuf.DescriptorProtos does not exist
import com.google.protobuf.DescriptorProtos.*;
```

what else do i need to install manually?
am i doing something fundamentally wrong?

**Comment by snodnipper** [comment]
Hi @jgravois, I have updated the project so that you can execute the following:

```console
./gradlew esri
./gradlew mapbox
```

That should give the output you require.

If you are hacking about then you might find that downloading [IntelliJ][1] and opening the build.gradle file from the output gets you going better in the longer term.  There is a gradle tab on the right by default, which should help you on your way.

<img width="37" alt="screen shot 2017-01-21 at 23 18 53" src="https://cloud.githubusercontent.com/assets/576719/22178503/080f49b0-e030-11e6-8ee0-96d58962366e.png">

Let me know if you run into further issues - it will be great once this is sorted!  Thanks.

[1]: https://www.jetbrains.com/idea/download/

**Comment by jgravois** [comment]
sorry it took me a few days to get back to this but i can repro the behavior you described after pulling down the latest.

1. `cd ./vt-source`
2. `./run.sh`
3. `cd temp`
4. `./gradlew mapbox && ./gradlew esri`

you mentioned that you were testing with our beta tiles and , but the behavior was the same when i substituted this [new one](https://basemaps.arcgis.com/v1/arcgis/rest/services/World_Basemap/VectorTileServer/tile/7/48/62.pbf) and the `1.0.1` vector_tile.proto.

thank you again for taking the time to put together this simplified repro case and to walk me through running it.  i've passed it on to the appropriate folks internally and hope to have some more information to share shortly.
