### ISSUE TITLE
logged as Esri BUG-000104019

### ISSUE THREAD

**Issue by jgravois** [snodnipper/vector-tile-esri-issues#2]
sorry for taking so long to follow up. this problem was confirmed and logged internally as
`BUG-000104019`.

the team had the following words of caution:

> BTW, you’re using Proto3 in some of these examples but the spec is based on Proto2 and they have some incompatibilities.  Haven’t actually tested this too much with respect to VTs, but beware.

thanks again for taking the time to report this problem and put together a simplified test case.

**Comment by snodnipper** [comment]
Sweet, thanks for getting back.

Regarding the Proto3 reference - I *believe* that the ESRI dev was looking at the `protobuf-java:3.1.0'` reference.  My understanding is that the v3 library should be [backwards compatible](https://groups.google.com/forum/#!topic/protobuf/wAqvtPLBsE8) and I *think* that because the [Mapbox Vector Tile spec](https://github.com/mapbox/vector-tile-spec/blob/ab55f2bd7b8c0af5d9a845e4bb0b133811ce3ccf/2.1/vector_tile.proto) does not have [oneof](https://developers.google.com/protocol-buffers/docs/proto3#backwards-compatibility-issues) references then we should be fine.

We were still using `proto2`to generate the code - just using the newer library, which should work with both v3 and v2 files afaik.

(I'll let you know if I discover otherwise)
